version: '3.8'

services:
  backend:
    build: .
    container_name: fiso-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=fiso_user
      - DB_PASSWORD=fiso_pass
      - DB_NAME=fiso_db
    volumes:
      - .:/app

  postgres:
    image: postgres:14
    container_name: fiso-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fiso_user
      POSTGRES_PASSWORD: fiso_pass
      POSTGRES_DB: fiso_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
